"""Visual-conditioned latent WAM modules for multimodal phases M1 and M2."""

from models.wam_multimodal.agent_factorized_flow_wam import (
    AgentFactorizedFlowWAM,
)
from models.wam_multimodal.block_causal_transformer import (
    BlockCausalWAM,
    BlockCausalWAMConfig,
    BlockCausalWAMOutput,
    UTF8TaskEncoder,
    build_block_causal_attention_mask,
)
from models.wam_multimodal.cross_agent_world_conditioned_flow import (
    CrossAgentWorldConditionedFlow,
    PredictedFutureLatents,
    WorldToFlowAdapterConfig,
    WorldToFlowResidualAdapter,
)

from models.wam_multimodal.latent_wam import (
    CapacityControl,
    LatentWAM,
    LatentWAMConfig,
    LatentWAMEncoding,
    LatentWAMOutput,
)
from models.wam_multimodal.latent_world_head import (
    ActionConditionedFutureLatentHead,
    CANONICAL_FUTURE_HORIZONS,
    FutureLatentHeadConfig,
)
from models.wam_multimodal.local_future_predictor import (
    LocalActionConditionedFuturePredictor,
    LocalFuturePredictorConfig,
)
from models.wam_multimodal.protected_hybrid_future_predictor import (
    ProtectedHybridFuturePrediction,
    ProtectedHybridFuturePredictor,
    exact_own_difference,
)
from models.wam_multimodal.protected_team_future_predictor import (
    ProtectedTeamFuturePredictor,
    ProtectedTeamFuturePredictorConfig,
)
from models.wam_multimodal.token_resampler import (
    PerceiverResampler,
    PerceiverResamplerConfig,
    SpatialVisualTokenAdapter,
    VisualAdapterOutput,
)
from models.wam_multimodal.team_shared_future_predictor import (
    TeamSharedFuturePrediction,
    TeamSharedFuturePredictor,
    TeamSharedFuturePredictorConfig,
)
from models.wam_multimodal.utility_calibrated_world_flow import (
    ActiveParentVelocityCache,
    ForcedEvidenceAudit,
    S4ActiveTeamFutureProvider,
    ScaleAlignedActiveWorldFlow,
    UtilityCalibratedWorldFlow,
    forced_evidence_velocity_errors,
    forced_group_distribution,
    world_utility_coupling_loss,
)
from models.wam_multimodal.vision_encoder import (
    DEFAULT_DINOV3_ENCODER,
    DEFAULT_DINOV3_CONFIG_SHA256,
    DEFAULT_DINOV3_MODEL_ID,
    DEFAULT_DINOV3_REVISION,
    DEFAULT_DINOV3_WEIGHTS_SHA256,
    DINOV3_ENCODER_SPECS,
    DINOV3_PREPROCESS_ID,
    DINOV3_RECTANGULAR_PREPROCESS_ID,
    DINOv3EncoderSpec,
    FrozenDINOv3Config,
    FrozenDINOv3Encoder,
    FrozenResNet18Config,
    FrozenResNet18Encoder,
    IMAGENET_RGB_MEAN,
    IMAGENET_RGB_STD,
    OFFICIAL_RESNET18_FILENAME,
    OFFICIAL_RESNET18_SHA256,
    VisionEncoderOutput,
    build_resnet18_classifier,
    canonical_json_sha256,
    default_resnet18_weights_path,
    sha256_file,
)
from models.wam_multimodal.world_evidence_router import (
    EVIDENCE_HORIZONS,
    EVIDENCE_SOURCES,
    EvidenceAdapterOutput,
    EvidenceRouterOutput,
    EvidenceTokens,
    FutureEvidenceRouter,
    LowRankEvidenceAdapterBank,
    S4WorldEvidenceProvider,
    UtilityCalibratedResidual,
    WorldEvidenceRouterConfig,
    group_index,
)

__all__ = [
    "ActionConditionedFutureLatentHead",
    "ActiveParentVelocityCache",
    "AgentFactorizedFlowWAM",
    "BlockCausalWAM",
    "BlockCausalWAMConfig",
    "BlockCausalWAMOutput",
    "CANONICAL_FUTURE_HORIZONS",
    "CapacityControl",
    "CrossAgentWorldConditionedFlow",
    "DEFAULT_DINOV3_ENCODER",
    "DEFAULT_DINOV3_CONFIG_SHA256",
    "DEFAULT_DINOV3_MODEL_ID",
    "DEFAULT_DINOV3_REVISION",
    "DEFAULT_DINOV3_WEIGHTS_SHA256",
    "DINOV3_ENCODER_SPECS",
    "DINOV3_PREPROCESS_ID",
    "DINOV3_RECTANGULAR_PREPROCESS_ID",
    "DINOv3EncoderSpec",
    "EVIDENCE_HORIZONS",
    "EVIDENCE_SOURCES",
    "EvidenceAdapterOutput",
    "EvidenceRouterOutput",
    "EvidenceTokens",
    "ForcedEvidenceAudit",
    "FrozenDINOv3Config",
    "FrozenDINOv3Encoder",
    "FrozenResNet18Config",
    "FrozenResNet18Encoder",
    "FutureLatentHeadConfig",
    "FutureEvidenceRouter",
    "IMAGENET_RGB_MEAN",
    "IMAGENET_RGB_STD",
    "LatentWAM",
    "LatentWAMConfig",
    "LatentWAMEncoding",
    "LatentWAMOutput",
    "LocalActionConditionedFuturePredictor",
    "LocalFuturePredictorConfig",
    "LowRankEvidenceAdapterBank",
    "OFFICIAL_RESNET18_FILENAME",
    "OFFICIAL_RESNET18_SHA256",
    "PerceiverResampler",
    "PredictedFutureLatents",
    "PerceiverResamplerConfig",
    "ProtectedHybridFuturePrediction",
    "ProtectedHybridFuturePredictor",
    "ProtectedTeamFuturePredictor",
    "ProtectedTeamFuturePredictorConfig",
    "S4ActiveTeamFutureProvider",
    "S4WorldEvidenceProvider",
    "ScaleAlignedActiveWorldFlow",
    "SpatialVisualTokenAdapter",
    "TeamSharedFuturePrediction",
    "TeamSharedFuturePredictor",
    "TeamSharedFuturePredictorConfig",
    "UTF8TaskEncoder",
    "UtilityCalibratedResidual",
    "UtilityCalibratedWorldFlow",
    "VisualAdapterOutput",
    "VisionEncoderOutput",
    "WorldToFlowAdapterConfig",
    "WorldToFlowResidualAdapter",
    "WorldEvidenceRouterConfig",
    "build_resnet18_classifier",
    "build_block_causal_attention_mask",
    "canonical_json_sha256",
    "default_resnet18_weights_path",
    "exact_own_difference",
    "forced_evidence_velocity_errors",
    "forced_group_distribution",
    "group_index",
    "sha256_file",
    "world_utility_coupling_loss",
]
