name: robofactory_six_task_image

image_shape: &image_shape [3, 224, 224]
shape_meta: &shape_meta
  obs:
    head_cam:
      shape: *image_shape
      type: rgb
      horizon: ${n_obs_steps}
    agent_pos:
      shape: [9]
      type: low_dim
      horizon: ${n_obs_steps}
  action:
    shape: [8]
    horizon: ${horizon}

dataset:
  _target_: maniflow.dataset.robotwin_image_dataset.RoboTwinImageDataset
  zarr_path: /workspace/bwa-baselines-runs/dp/six_tasks_agent0.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 20260820
  val_ratio: 0.02
  max_train_episodes: null
