[program:bwa-openvla-supervisor]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/bwa-openvla-supervisor.sh
autostart=true
autorestart=unexpected
startsecs=2
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
