[program:p1_place_food_update]
command=/venv/robofactory-act/bin/hf download zeno-ai/robofactory-place-food-multiview --repo-type dataset --revision c912342823d41e3b1969311ec8c34e20aab22ea4 --local-dir /workspace/datasets/robofactory_multitask/.place_food-c912342823d41e3b1969311ec8c34e20aab22ea4 --max-workers 8
directory=/workspace
environment=HF_HOME="/workspace/.cache/huggingface",HF_HUB_DISABLE_TELEMETRY="1"
autostart=false
autorestart=unexpected
startsecs=5
startretries=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
redirect_stderr=true
stdout_logfile=/var/log/portal/p1_place_food_update.log
stdout_logfile_maxbytes=104857600
stdout_logfile_backups=3

