[program:mars-rdt-supervisor]
environment=PROC_NAME="%(program_name)s"
command=/workspace/repos/before-we-act/deployment/rdt_mars/mars-rdt-supervisor.sh
directory=/workspace/repos/before-we-act
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
