[program:bicoord_base_assets]
command=/opt/supervisor-scripts/bicoord-base-assets.sh
autostart=false
autorestart=unexpected
startsecs=10
startretries=5
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=PROC_NAME="%(program_name)s"
