"""Simulation bridge for deployable FE-PC-WAM observations.

The carry environment exposes simulator truth and several legacy observation
vectors.  This module is the single bridge that is allowed to consume that
truth during closed-loop evaluation.  Its output is limited to
``LocalObservationPacket`` objects generated by ``LocalObservationSimulator``;
teammate state and the legacy global observation are never copied into a
packet.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

import numpy as np

from data.local_observation import (
    LocalObservationPacket,
    LocalObservationSimulator,
    LocalObservationSpec,
    PrivilegedAgentState,
    SensorSimulationConfig,
)


_NUM_AGENTS = 2
_ACTION_DIM = 4


def _action_matrix(action: np.ndarray) -> tuple[np.ndarray, tuple[int, ...]]:
    """Validate an action and return a copied ``(2, 4)`` float32 view."""

    value = np.asarray(action, dtype=np.float32)
    original_shape = value.shape
    if original_shape not in {(_NUM_AGENTS * _ACTION_DIM,), (_NUM_AGENTS, _ACTION_DIM)}:
        raise ValueError(
            "joint action must have shape (8,) or (2, 4), "
            f"got {original_shape}"
        )
    if not np.all(np.isfinite(value)):
        raise ValueError("joint action contains non-finite values")
    return value.reshape(_NUM_AGENTS, _ACTION_DIM).copy(), original_shape


def _robot_yaws(observation_or_yaws: Mapping[str, Any] | np.ndarray) -> np.ndarray:
    """Extract the two current robot yaws from an environment obs or yaw pair."""

    if isinstance(observation_or_yaws, Mapping):
        if "global_state" not in observation_or_yaws:
            raise KeyError("environment observation is missing 'global_state'")
        state = np.asarray(observation_or_yaws["global_state"], dtype=np.float32)
        if state.ndim != 1 or state.shape[0] < 6:
            raise ValueError(
                "observation['global_state'] must be a vector with at least 6 values"
            )
        yaws = state[[2, 5]]
    else:
        yaws = np.asarray(observation_or_yaws, dtype=np.float32)
        if yaws.shape != (_NUM_AGENTS,):
            raise ValueError(f"robot yaws must have shape (2,), got {yaws.shape}")
    if not np.all(np.isfinite(yaws)):
        raise ValueError("robot yaws contain non-finite values")
    return yaws.astype(np.float32, copy=True)


def world_action_to_ego(
    action: np.ndarray,
    observation_or_yaws: Mapping[str, Any] | np.ndarray,
) -> np.ndarray:
    """Rotate two normalized planar actions from world to sender ego frames.

    ``vx`` and ``vy`` are rotated.  Angular velocity and grip are invariant.
    The returned array has the same shape as ``action`` (either ``(8,)`` or
    ``(2, 4)``).
    """

    result, original_shape = _action_matrix(action)
    yaws = _robot_yaws(observation_or_yaws)
    for agent_id, yaw in enumerate(yaws):
        c, s = float(np.cos(yaw)), float(np.sin(yaw))
        world_x, world_y = result[agent_id, :2].copy()
        result[agent_id, 0] = c * world_x + s * world_y
        result[agent_id, 1] = -s * world_x + c * world_y
    return result.reshape(original_shape).astype(np.float32, copy=False)


def ego_action_to_world(
    action: np.ndarray,
    observation_or_yaws: Mapping[str, Any] | np.ndarray,
) -> np.ndarray:
    """Rotate two normalized planar actions from sender ego to world frames.

    This is the exact inverse of :func:`world_action_to_ego` up to floating
    point precision and preserves ``(8,)`` versus ``(2, 4)`` shape.
    """

    result, original_shape = _action_matrix(action)
    yaws = _robot_yaws(observation_or_yaws)
    for agent_id, yaw in enumerate(yaws):
        c, s = float(np.cos(yaw)), float(np.sin(yaw))
        ego_x, ego_y = result[agent_id, :2].copy()
        result[agent_id, 0] = c * ego_x - s * ego_y
        result[agent_id, 1] = s * ego_x + c * ego_y
    return result.reshape(original_shape).astype(np.float32, copy=False)


class SimulationAdapter:
    """Create strict deployable packets from ``TwoRobotCarry`` simulator data.

    The adapter deliberately stores only the latest ego-frame base twists.  It
    does not retain the input observation, global state, object truth, or any
    teammate state.  Call :meth:`reset` at every environment reset so sensor
    RNG and stale-measurement caches are episode deterministic.
    """

    def __init__(
        self,
        env: Any,
        sensor_config: SensorSimulationConfig | None = None,
        spec: LocalObservationSpec | None = None,
        seed: int = 0,
    ) -> None:
        self.env = env
        self.spec = spec or LocalObservationSpec(joint_dim=0, force_dim=1)
        if self.spec.joint_dim != 0 or self.spec.force_dim != 1:
            raise ValueError(
                "TwoRobotCarry  simulation requires LocalObservationSpec("
                "joint_dim=0, force_dim=1)"
            )

        cfg = getattr(env, "cfg", None)
        if cfg is None:
            raise TypeError("env must expose a CarryEnvConfig-compatible 'cfg' attribute")
        for name in ("control_dt", "goal_y", "max_action_v", "max_action_w"):
            if not hasattr(cfg, name):
                raise TypeError(f"env.cfg is missing required attribute {name!r}")

        self.sensor_config = sensor_config or SensorSimulationConfig(
            control_dt=float(cfg.control_dt)
        )
        self.sensor = LocalObservationSimulator(
            spec=self.spec,
            config=self.sensor_config,
            seed=seed,
        )
        self._base_twists = np.zeros((_NUM_AGENTS, 3), dtype=np.float32)

    @property
    def base_twists(self) -> np.ndarray:
        """Latest physical ``[vx, vy, wz]`` values in each robot's ego frame."""

        return self._base_twists.copy()

    def reset(self, seed: int | None = None) -> None:
        """Reset base motion and sensor RNG/cache for a new episode."""

        self._base_twists.fill(0.0)
        self.sensor.reset(seed=seed)

    def packets(
        self,
        obs: Mapping[str, Any],
        info: Mapping[str, Any],
        previous_world_action: np.ndarray | None = None,
    ) -> tuple[LocalObservationPacket, LocalObservationPacket]:
        """Generate the two current strict-local observation packets.

        ``previous_world_action`` is the normalized action already applied to
        the environment to obtain ``obs``.  It supplies base velocity and local
        grasp state.  On the initial observation it must be omitted, yielding
        zero twist and open grippers.
        """

        if not isinstance(obs, Mapping):
            raise TypeError("obs must be a mapping returned by TwoRobotCarry")
        if not isinstance(info, Mapping):
            raise TypeError("info must be a mapping returned by TwoRobotCarry")

        robot_poses, object_pose = self._privileged_poses(obs)
        applied_action = self._applied_action(previous_world_action)
        self._base_twists = self._base_twists_from_action(applied_action, obs)

        goal_world = np.asarray(
            [0.0, float(self.env.cfg.goal_y), 0.0], dtype=np.float32
        )
        result: list[LocalObservationPacket] = []
        for agent_id in range(_NUM_AGENTS):
            truth = PrivilegedAgentState(
                ego_pose_world=robot_poses[agent_id],
                object_pose_world=object_pose,
                task_goal_world=goal_world,
                base_twist=self._base_twists[agent_id],
                joint_position=np.zeros(0, dtype=np.float32),
                joint_velocity=np.zeros(0, dtype=np.float32),
                joint_torque=np.zeros(0, dtype=np.float32),
                local_force=np.asarray(
                    [self._local_force(info, agent_id)], dtype=np.float32
                ),
                contact=self._local_contact(info, agent_id),
                grasp=bool(applied_action[agent_id, 3] > 0.5),
            )
            visible_key = f"object_visible_robot_{agent_id}"
            object_visible = bool(info.get(visible_key, True))
            result.append(
                self.sensor.observe(
                    agent_id,
                    truth,
                    object_visible=object_visible,
                )
            )

        return result[0], result[1]

    @staticmethod
    def _privileged_poses(obs: Mapping[str, Any]) -> tuple[np.ndarray, np.ndarray]:
        if "global_state" not in obs:
            raise KeyError("environment observation is missing 'global_state'")
        if "object" not in obs:
            raise KeyError("environment observation is missing 'object'")

        state = np.asarray(obs["global_state"], dtype=np.float32)
        if state.ndim != 1 or state.shape[0] < 6:
            raise ValueError(
                "observation['global_state'] must be a vector with at least 6 values"
            )
        object_pose = np.asarray(obs["object"], dtype=np.float32)
        if object_pose.shape != (3,):
            raise ValueError(
                f"observation['object'] must have shape (3,), got {object_pose.shape}"
            )
        robot_poses = np.stack((state[0:3], state[3:6]), axis=0).astype(np.float32)
        if not np.all(np.isfinite(robot_poses)) or not np.all(np.isfinite(object_pose)):
            raise ValueError("simulator poses contain non-finite values")
        return robot_poses, object_pose.copy()

    @staticmethod
    def _local_contact(info: Mapping[str, Any], agent_id: int) -> bool:
        # Never fall back to the global MuJoCo contact count: that would reveal
        # a peer-only contact to this agent.  The environment must expose the
        # two tactile flags explicitly.
        if "local_contact_agents" not in info:
            raise KeyError("info is missing per-agent 'local_contact_agents'")
        values = np.asarray(info["local_contact_agents"], dtype=np.float32)
        if values.shape != (_NUM_AGENTS,) or not np.all(np.isfinite(values)):
            raise ValueError("local_contact_agents must be two finite flags")
        return bool(values[agent_id] > 0.5)

    @staticmethod
    def _local_force(info: Mapping[str, Any], agent_id: int) -> float:
        if "local_force_agents" not in info:
            raise KeyError("info is missing per-agent 'local_force_agents'")
        values = np.asarray(info["local_force_agents"], dtype=np.float32)
        if (
            values.shape != (_NUM_AGENTS,)
            or not np.all(np.isfinite(values))
            or np.any(values < 0.0)
            or np.any(values > 1.0)
        ):
            raise ValueError("local_force_agents must be two finite values in [0, 1]")
        return float(values[agent_id])

    @staticmethod
    def _applied_action(previous_world_action: np.ndarray | None) -> np.ndarray:
        if previous_world_action is None:
            return np.zeros((_NUM_AGENTS, _ACTION_DIM), dtype=np.float32)
        action, _ = _action_matrix(previous_world_action)
        # TwoRobotCarry clips normalized commands before applying them.
        return np.clip(action, -1.0, 1.0).astype(np.float32)

    def _base_twists_from_action(
        self,
        action_world: np.ndarray,
        obs: Mapping[str, Any],
    ) -> np.ndarray:
        action_ego = world_action_to_ego(action_world, obs).reshape(
            _NUM_AGENTS, _ACTION_DIM
        )
        twist = np.empty((_NUM_AGENTS, 3), dtype=np.float32)
        twist[:, :2] = action_ego[:, :2] * float(self.env.cfg.max_action_v)
        twist[:, 2] = action_ego[:, 2] * float(self.env.cfg.max_action_w)
        return twist


__all__ = [
    "SimulationAdapter",
    "ego_action_to_world",
    "world_action_to_ego",
]
